<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-11T23:52:36 IST" name="BasicMaven" finished-at="2024-09-11T23:53:06 IST" duration-ms="30198">
    <groups>
    </groups>
    <test started-at="2024-09-11T23:52:36 IST" name="BankingApp Test" finished-at="2024-09-11T23:53:06 IST" duration-ms="30198">
      <class name="com.BasicMaven.testCases.TC_LoginTest_001">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.BasicMaven.testCases.TC_LoginTest_001@1a04f701]" started-at="2024-09-11T23:52:37 IST" name="setup" finished-at="2024-09-11T23:52:44 IST" duration-ms="7412" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[EDGE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest()[pri:0, instance:com.BasicMaven.testCases.TC_LoginTest_001@1a04f701]" started-at="2024-09-11T23:52:44 IST" name="loginTest" finished-at="2024-09-11T23:52:46 IST" duration-ms="1702" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.BasicMaven.testCases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.BasicMaven.testCases.TC_LoginTest_001@1a04f701]" started-at="2024-09-11T23:52:46 IST" name="tearDown" finished-at="2024-09-11T23:52:47 IST" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.BasicMaven.testCases.TC_LoginTest_001 -->
      <class name="com.BasicMaven.testCases.TC_AddCustomerTest_003">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.BasicMaven.testCases.TC_AddCustomerTest_003@419c5f1a]" started-at="2024-09-11T23:52:47 IST" name="setup" finished-at="2024-09-11T23:52:53 IST" duration-ms="6060" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[EDGE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addNewCustomer()[pri:0, instance:com.BasicMaven.testCases.TC_AddCustomerTest_003@419c5f1a]" started-at="2024-09-11T23:52:53 IST" name="addNewCustomer" finished-at="2024-09-11T23:53:06 IST" duration-ms="13345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.BasicMaven.testCases.TC_AddCustomerTest_003@419c5f1a]" started-at="2024-09-11T23:53:06 IST" name="tearDown" finished-at="2024-09-11T23:53:06 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.BasicMaven.testCases.TC_AddCustomerTest_003 -->
    </test> <!-- BankingApp Test -->
  </suite> <!-- BasicMaven -->
</testng-results>
